# Generated by Django 4.1.6 on 2023-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='start_date',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
