# Generated by Django 4.1.6 on 2023-03-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialarticle',
            old_name='is_todays_pick',
            new_name='todays_pick',
        ),
        migrations.RenameField(
            model_name='specialarticle',
            old_name='is_top_story',
            new_name='top_story',
        ),
    ]
