# Generated by Django 4.1.6 on 2023-03-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='archive',
            new_name='archived',
        ),
        migrations.AddField(
            model_name='article',
            name='editor_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='todays_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='top_story',
            field=models.BooleanField(default=False),
        ),
    ]
