# Generated by Django 4.1.6 on 2023-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_rename_is_todays_pick_specialarticle_todays_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialarticle',
            name='editor_note',
            field=models.BooleanField(default=False),
        ),
    ]
