# Generated by Django 4.1.6 on 2023-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_specialarticle_editor_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialarticle',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
