# Generated by Django 4.1.6 on 2023-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_article_archive_specialarticle_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialarticle',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
