# Generated by Django 4.1.6 on 2023-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_article_issue_alter_specialarticle_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialarticle',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
