# Generated by Django 4.1.6 on 2023-03-19 19:48

from django.db import migrations, models
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=magazine.models.get_category_cover_image),
        ),
    ]
