# Generated by Django 4.1.6 on 2023-03-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
